// src/ServiceStackVS/ProjectTemplates/TypeScriptReact/Host/src/app.tsx
﻿import "es6-shim";
import * as ReactDOM from 'react-dom';
import * as React from 'react';
import HelloWorld from './HelloWorld';

var LINKS = ["Link 1", "Link 2", "Link 3"];

class App extends React.Component<any, any> {
    constructor(props) {
        super(props);
        this.state = { activeLink: "Link 1" };
    }
    render() {
        return (
            <div>
                <nav className="navbar navbar-toggleable-md navbar-inverse bg-inverse">
                    <div className="container">
                        <a className="navbar-brand" href="#">
                            <i className="fa fa-code" aria-hidden="true"></i>
                            <span style={{ paddingLeft: 5 }}>$safeprojectname$</span>
                        </a>
                        <div className="collapse navbar-collapse">
                            <ul className="navbar-nav mr-auto">
                                {LINKS.map(x =>
                                    (<li key={x} className={"nav-item " + (this.state.activeLink == x ? "active" : "")}
                                        onClick={e => this.setState({ activeLink: x })}>
                                        <a className="nav-link" href="#">{x}</a>
                                    </li>)
                                )}
                            </ul>
                        </div>
                    </div>
                </nav>

                <div className="container">
                    <div className="row" style={{ margin: "10px 0" }}>
                        <div id="content">
                            <HelloWorld />
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

ReactDOM.render(<App />, document.getElementById("body"));

// src/ServiceStackVS/ProjectTemplates/AppVue/Host/src/App.vue
﻿<template>
<div>
    <nav class="navbar navbar-toggleable-md navbar-inverse">
        <div class="container">
            <a class="navbar-brand" href="#">
                <i class="fa fa-code" aria-hidden="true"></i>
                $safeprojectname$
            </a>

            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                  <router-link tag="li" class="nav-item" to="/" exact>
                    <a class="nav-link">Home</a>
                  </router-link>
                  <router-link tag="li" class="nav-item" to="/view1">
                    <a class="nav-link">View1</a>
                  </router-link>
                  <router-link tag="li" class="nav-item" to="/view2">
                    <a class="nav-link">View2</a>
                  </router-link>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row" style="margin:10px 0">
            <div id="content">
                <router-view></router-view>
            </div>
        </div>
    </div>

    <h4 style="position: absolute; bottom: 20px; width: 100%; text-align: center">
        <img src="./assets/img/logo.png" />
        <a :href="url">Learn about this Vue VS.NET template</a>
    </h4>
</div>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  name: 'app-root',
  data() {
    return { url: "https://servicestack.net/vs-templates/VueApp" }
  }
});
</script>
