// src/ServiceStackVS/ProjectTemplates/AppReactDesktop/Host/src/Home/Home.tsx
﻿import './home.scss';

import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { client } from '../shared';
import { Hello } from '../dtos';

export default class Home extends React.Component<any, any> {
    constructor(props, context) {
        super(props, context);
        this.state = { msg: '' };
    }

    async nameChanged(name: string) {
        if (name) {
            let request = new Hello();
            request.name = name;
            let r = await client.get(request);
            this.setState({ msg: r.result });
        } else {
            this.setState({ msg: '' });
        }
    }

    render() {
        return (
            <div className="form-group">
                <input className="form-control" type="text" placeholder="Your name"
                    onChange={e => this.nameChanged((e.target as HTMLInputElement).value)} />
                <h3 className="result">{this.state.msg}</h3>
            </div>);
    }
}

// src/ServiceStackVS/ProjectTemplates/AppVue/Host/src/home/Home.vue
﻿<template>
    <div class="form-group">
        <input class="form-control" type="text" placeholder="Your name"
               v-on:keyup="nameChanged($event.target.value)" />
        <h3 class="result">{{ result }}</h3>
    </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { client } from '../shared';
import { Hello } from '../dtos';

export default Vue.extend({
  props: ['initResult'],
  data: function() {
    return { result: this.initResult }
  },
  methods: {
    async nameChanged(name:string) {
        if (name) {
            let request = new Hello();
            request.name = name;
            let r = await client.get(request);
            this.result = r.result;
        } else {
            this.result = '';
        }
    }
  }
});
</script>

<style lang="scss">
@import '../app.scss';

.result {
    margin: 10px;
    color: darken($navbar-background, 10%);
}
</style>
